name: provenance_wallet
description: The Provenance Blockchain Wallet provides users in all categories the ability to hold and exchange HASH, the native token on the Provenance Blockchain, and connect to next generation financial service dApps powered by blockchain through a simple QR scanning process.

publish_to: "none"

version: 1.1.8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  collection: ^1.15.0
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  decimal: ^2.1.0
  dio: ^4.0.0
  faker: ^2.0.0
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  firebase_dynamic_links: ^4.2.2
  firebase_messaging: ^11.3.0
  firebase_remote_config: ^2.0.6
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.17.0
  flutter_native_splash: ^1.2.1
  flutter_phoenix: ^1.0.0
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: 4.6.0
  logger: ^1.0.0
  mobile_scanner:
    git:
      url: https://github.com/smsimone/mobile_scanner.git
      ref: b4c0309a7d8bcf66020058b4e5eb9ff68c44f42d
  package_info_plus: ^1.4.2
  path:
  path_provider: ^2.0.10
  pretty_json: ^2.0.0
  prov_wallet_flutter:
    path: packages/prov_wallet_flutter
  provenance_dart:
    git:
      url: https://github.com/provenance-io/provenance-dart.git
      ref: develop
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  rxdart: ^0.27.3
  sembast: ^3.2.0
  sembast_web: ^2.0.1+1
  share_plus: ^4.0.7
  shared_preferences: ^2.0.6
  sqflite: ^2.0.2
  uni_links: ^0.5.1
  url_launcher: ^6.0.10
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.9.0
  flutter_launcher_icons: 0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mockito: ^5.1.0

# different icons per flavor are supported by creating files with the name flutter_launcher_icons-<flavor>.yaml
flutter_icons:
  android: true
  ios: false
  remove_alpha_ios: true
  image_path: "assets/app_icon/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon/adaptive_foreground.png"
  adaptive_icon_background: "assets/app_icon/adaptive_background.png"

flutter_native_splash:
  background_image: "assets/splash/background.png"
  image: "assets/splash/foreground.png"
  fullscreen: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/splash/

  fonts:
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono/overpass-mono-regular.ttf
    - family: GothicA1
      fonts:
        - asset: fonts/GothicA1/GothicA1-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/GothicA1/GothicA1-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/GothicA1/GothicA1-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/GothicA1/GothicA1-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/GothicA1/GothicA1-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/GothicA1/GothicA1-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/GothicA1/GothicA1-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/GothicA1/GothicA1-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/GothicA1/GothicA1-Thin.ttf
          weight: 100
          style: normal
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
