// Mocks generated by Mockito 5.3.0 from annotations
// in provenance_wallet/test/screens/home/accounts/account_cell_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:provenance_dart/proto.dart' as _i9;
import 'package:provenance_dart/wallet.dart' as _i7;
import 'package:provenance_wallet/clients/multi_sig_client/dto/multi_sig_status.dart'
    as _i11;
import 'package:provenance_wallet/clients/multi_sig_client/models/multi_sig_pending_tx.dart'
    as _i10;
import 'package:provenance_wallet/clients/multi_sig_client/models/multi_sig_register_result.dart'
    as _i8;
import 'package:provenance_wallet/clients/multi_sig_client/models/multi_sig_remote_account.dart'
    as _i6;
import 'package:provenance_wallet/clients/multi_sig_client/models/multi_sig_signer.dart'
    as _i14;
import 'package:provenance_wallet/clients/multi_sig_client/models/multi_sig_update_result.dart'
    as _i12;
import 'package:provenance_wallet/clients/multi_sig_client/multi_sig_client.dart'
    as _i4;
import 'package:provenance_wallet/services/account_service/account_service.dart'
    as _i3;
import 'package:provenance_wallet/services/http_client.dart' as _i2;
import 'package:provenance_wallet/services/models/account.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpClient_0 extends _i1.SmartFake implements _i2.HttpClient {
  _FakeHttpClient_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAccountServiceEvents_1 extends _i1.SmartFake
    implements _i3.AccountServiceEvents {
  _FakeAccountServiceEvents_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [MultiSigClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiSigClient extends _i1.Mock implements _i4.MultiSigClient {
  MockMultiSigClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.MultiSigRemoteAccount?> create(
          {String? name,
          int? cosignerCount,
          int? threshold,
          _i7.PublicKey? publicKey}) =>
      (super.noSuchMethod(
              Invocation.method(#create, [], {
                #name: name,
                #cosignerCount: cosignerCount,
                #threshold: threshold,
                #publicKey: publicKey
              }),
              returnValue: _i5.Future<_i6.MultiSigRemoteAccount?>.value())
          as _i5.Future<_i6.MultiSigRemoteAccount?>);
  @override
  _i5.Future<_i8.MultiSigRegisterResult?> register(
          {String? inviteId, _i7.PublicKey? publicKey}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #register, [], {#inviteId: inviteId, #publicKey: publicKey}),
              returnValue: _i5.Future<_i8.MultiSigRegisterResult?>.value())
          as _i5.Future<_i8.MultiSigRegisterResult?>);
  @override
  _i5.Future<List<_i6.MultiSigRemoteAccount>?> getAccounts(
          {String? address, _i7.Coin? coin}) =>
      (super.noSuchMethod(
          Invocation.method(#getAccounts, [], {#address: address, #coin: coin}),
          returnValue:
              _i5.Future<List<_i6.MultiSigRemoteAccount>?>.value()) as _i5
          .Future<List<_i6.MultiSigRemoteAccount>?>);
  @override
  _i5.Future<_i6.MultiSigRemoteAccount?> getAccount(
          {String? remoteId, String? signerAddress, _i7.Coin? coin}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccount, [], {
                #remoteId: remoteId,
                #signerAddress: signerAddress,
                #coin: coin
              }),
              returnValue: _i5.Future<_i6.MultiSigRemoteAccount?>.value())
          as _i5.Future<_i6.MultiSigRemoteAccount?>);
  @override
  _i5.Future<_i6.MultiSigRemoteAccount?> getAccountByInvite(
          {String? inviteId, _i7.Coin? coin}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAccountByInvite, [], {#inviteId: inviteId, #coin: coin}),
              returnValue: _i5.Future<_i6.MultiSigRemoteAccount?>.value())
          as _i5.Future<_i6.MultiSigRemoteAccount?>);
  @override
  _i5.Future<String?> createTx(
          {String? multiSigAddress,
          String? signerAddress,
          _i7.Coin? coin,
          _i9.TxBody? txBody,
          _i9.Fee? fee}) =>
      (super.noSuchMethod(
          Invocation.method(#createTx, [], {
            #multiSigAddress: multiSigAddress,
            #signerAddress: signerAddress,
            #coin: coin,
            #txBody: txBody,
            #fee: fee
          }),
          returnValue: _i5.Future<String?>.value()) as _i5.Future<String?>);
  @override
  _i5.Future<List<_i10.MultiSigPendingTx>?> getPendingTxs(
          {List<String>? signerAddresses}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getPendingTxs, [], {#signerAddresses: signerAddresses}),
              returnValue: _i5.Future<List<_i10.MultiSigPendingTx>?>.value())
          as _i5.Future<List<_i10.MultiSigPendingTx>?>);
  @override
  _i5.Future<List<_i10.MultiSigPendingTx>?> getCreatedTxs(
          {List<String>? signerAddresses, _i11.MultiSigStatus? status}) =>
      (super.noSuchMethod(
              Invocation.method(#getCreatedTxs, [],
                  {#signerAddresses: signerAddresses, #status: status}),
              returnValue: _i5.Future<List<_i10.MultiSigPendingTx>?>.value())
          as _i5.Future<List<_i10.MultiSigPendingTx>?>);
  @override
  _i5.Future<bool> signTx(
          {String? signerAddress,
          _i7.Coin? coin,
          String? txUuid,
          String? signatureBytes,
          bool? declineTx}) =>
      (super.noSuchMethod(
          Invocation.method(#signTx, [], {
            #signerAddress: signerAddress,
            #coin: coin,
            #txUuid: txUuid,
            #signatureBytes: signatureBytes,
            #declineTx: declineTx
          }),
          returnValue: _i5.Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i12.MultiSigUpdateResult> updateTxResult(
          {String? txUuid, String? txHash, _i7.Coin? coin}) =>
      (super.noSuchMethod(
              Invocation.method(#updateTxResult, [],
                  {#txUuid: txUuid, #txHash: txHash, #coin: coin}),
              returnValue: _i5.Future<_i12.MultiSigUpdateResult>.value(
                  _i12.MultiSigUpdateResult.success))
          as _i5.Future<_i12.MultiSigUpdateResult>);
  @override
  _i5.Future<_i2.HttpClient> getClient(_i7.Coin? coin) => (super.noSuchMethod(
          Invocation.method(#getClient, [coin]),
          returnValue: _i5.Future<_i2.HttpClient>.value(
              _FakeHttpClient_0(this, Invocation.method(#getClient, [coin]))))
      as _i5.Future<_i2.HttpClient>);
}

/// A class which mocks [AccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountService extends _i1.Mock implements _i3.AccountService {
  MockAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AccountServiceEvents get events =>
      (super.noSuchMethod(Invocation.getter(#events),
              returnValue:
                  _FakeAccountServiceEvents_1(this, Invocation.getter(#events)))
          as _i3.AccountServiceEvents);
  @override
  _i5.Future<_i13.Account?> getAccount(String? id) =>
      (super.noSuchMethod(Invocation.method(#getAccount, [id]),
              returnValue: _i5.Future<_i13.Account?>.value())
          as _i5.Future<_i13.Account?>);
  @override
  _i5.Future<_i13.Account?> selectFirstAccount() =>
      (super.noSuchMethod(Invocation.method(#selectFirstAccount, []),
              returnValue: _i5.Future<_i13.Account?>.value())
          as _i5.Future<_i13.Account?>);
  @override
  _i5.Future<_i13.TransactableAccount?> selectAccount({String? id}) =>
      (super.noSuchMethod(Invocation.method(#selectAccount, [], {#id: id}),
              returnValue: _i5.Future<_i13.TransactableAccount?>.value())
          as _i5.Future<_i13.TransactableAccount?>);
  @override
  _i5.Future<_i13.TransactableAccount?> getSelectedAccount() =>
      (super.noSuchMethod(Invocation.method(#getSelectedAccount, []),
              returnValue: _i5.Future<_i13.TransactableAccount?>.value())
          as _i5.Future<_i13.TransactableAccount?>);
  @override
  _i5.Future<List<_i13.Account>> getAccounts() => (super.noSuchMethod(
          Invocation.method(#getAccounts, []),
          returnValue: _i5.Future<List<_i13.Account>>.value(<_i13.Account>[]))
      as _i5.Future<List<_i13.Account>>);
  @override
  _i5.Future<List<_i13.BasicAccount>> getBasicAccounts() => (super.noSuchMethod(
          Invocation.method(#getBasicAccounts, []),
          returnValue:
              _i5.Future<List<_i13.BasicAccount>>.value(<_i13.BasicAccount>[]))
      as _i5.Future<List<_i13.BasicAccount>>);
  @override
  _i5.Future<List<_i13.TransactableAccount>> getTransactableAccounts() =>
      (super.noSuchMethod(Invocation.method(#getTransactableAccounts, []),
              returnValue: _i5.Future<List<_i13.TransactableAccount>>.value(
                  <_i13.TransactableAccount>[]))
          as _i5.Future<List<_i13.TransactableAccount>>);
  @override
  _i5.Future<_i13.Account?> renameAccount({String? id, String? name}) =>
      (super.noSuchMethod(
              Invocation.method(#renameAccount, [], {#id: id, #name: name}),
              returnValue: _i5.Future<_i13.Account?>.value())
          as _i5.Future<_i13.Account?>);
  @override
  _i5.Future<_i13.BasicAccount?> addAccount(
          {List<String>? phrase, String? name, _i7.Coin? coin}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #addAccount, [], {#phrase: phrase, #name: name, #coin: coin}),
              returnValue: _i5.Future<_i13.BasicAccount?>.value())
          as _i5.Future<_i13.BasicAccount?>);
  @override
  _i5.Future<_i13.MultiAccount?> addMultiAccount(
          {String? name,
          _i7.Coin? coin,
          String? linkedAccountId,
          String? remoteId,
          int? cosignerCount,
          int? signaturesRequired,
          List<String>? inviteIds,
          List<_i14.MultiSigSigner>? signers}) =>
      (super.noSuchMethod(
              Invocation.method(#addMultiAccount, [], {
                #name: name,
                #coin: coin,
                #linkedAccountId: linkedAccountId,
                #remoteId: remoteId,
                #cosignerCount: cosignerCount,
                #signaturesRequired: signaturesRequired,
                #inviteIds: inviteIds,
                #signers: signers
              }),
              returnValue: _i5.Future<_i13.MultiAccount?>.value())
          as _i5.Future<_i13.MultiAccount?>);
  @override
  _i5.Future<_i13.MultiTransactableAccount?> activateMultiAccount(
          {String? id, List<_i14.MultiSigSigner>? signers}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #activateMultiAccount, [], {#id: id, #signers: signers}),
              returnValue: _i5.Future<_i13.MultiTransactableAccount?>.value())
          as _i5.Future<_i13.MultiTransactableAccount?>);
  @override
  _i5.Future<_i13.Account?> removeAccount({String? id}) =>
      (super.noSuchMethod(Invocation.method(#removeAccount, [], {#id: id}),
              returnValue: _i5.Future<_i13.Account?>.value())
          as _i5.Future<_i13.Account?>);
  @override
  _i5.Future<List<_i13.Account>> resetAccounts() => (super.noSuchMethod(
          Invocation.method(#resetAccounts, []),
          returnValue: _i5.Future<List<_i13.Account>>.value(<_i13.Account>[]))
      as _i5.Future<List<_i13.Account>>);
  @override
  _i5.Future<_i7.PrivateKey?> loadKey(String? accountId) =>
      (super.noSuchMethod(Invocation.method(#loadKey, [accountId]),
              returnValue: _i5.Future<_i7.PrivateKey?>.value())
          as _i5.Future<_i7.PrivateKey?>);
  @override
  _i5.Future<bool> isValidWalletConnectData(String? qrData) => (super
      .noSuchMethod(Invocation.method(#isValidWalletConnectData, [qrData]),
          returnValue: _i5.Future<bool>.value(false)) as _i5.Future<bool>);
}
