// Mocks generated by Mockito 5.1.0 from annotations
// in provenance_wallet/test/screens/send_flow/send_amount/send_amount_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:flutter/src/foundation/diagnostics.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:provenance_wallet/screens/send_flow/model/send_asset.dart'
    as _i4;
import 'package:provenance_wallet/screens/send_flow/send_amount/send_amount_bloc.dart'
    as _i5;
import 'package:provenance_wallet/services/models/wallet_details.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWalletDetails_0 extends _i1.Fake implements _i2.WalletDetails {
  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeSendAsset_1 extends _i1.Fake implements _i4.SendAsset {}

/// A class which mocks [SendAmountBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendAmountBloc extends _i1.Mock implements _i5.SendAmountBloc {
  MockSendAmountBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WalletDetails get walletDetails =>
      (super.noSuchMethod(Invocation.getter(#walletDetails),
          returnValue: _FakeWalletDetails_0()) as _i2.WalletDetails);
  @override
  _i4.SendAsset get asset => (super.noSuchMethod(Invocation.getter(#asset),
      returnValue: _FakeSendAsset_1()) as _i4.SendAsset);
  @override
  String get receivingAddress =>
      (super.noSuchMethod(Invocation.getter(#receivingAddress), returnValue: '')
          as String);
  @override
  _i6.Stream<_i5.SendAmountBlocState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i5.SendAmountBlocState>.empty())
          as _i6.Stream<_i5.SendAmountBlocState>);
  @override
  void init() => super.noSuchMethod(Invocation.method(#init, []),
      returnValueForMissingStub: null);
  @override
  _i6.Future<void> showNext(String? note, String? amount) =>
      (super.noSuchMethod(Invocation.method(#showNext, [note, amount]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
}
