// Mocks generated by Mockito 5.3.0 from annotations
// in provenance_wallet/test/screens/send_flow/send_amount/send_amount_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:provenance_wallet/screens/send_flow/model/send_asset.dart'
    as _i3;
import 'package:provenance_wallet/screens/send_flow/send_amount/send_amount_bloc.dart'
    as _i4;
import 'package:provenance_wallet/services/models/account.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransactableAccount_0 extends _i1.SmartFake
    implements _i2.TransactableAccount {
  _FakeTransactableAccount_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSendAsset_1 extends _i1.SmartFake implements _i3.SendAsset {
  _FakeSendAsset_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [SendAmountBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendAmountBloc extends _i1.Mock implements _i4.SendAmountBloc {
  MockSendAmountBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TransactableAccount get account =>
      (super.noSuchMethod(Invocation.getter(#account),
              returnValue:
                  _FakeTransactableAccount_0(this, Invocation.getter(#account)))
          as _i2.TransactableAccount);
  @override
  _i3.SendAsset get asset => (super.noSuchMethod(Invocation.getter(#asset),
          returnValue: _FakeSendAsset_1(this, Invocation.getter(#asset)))
      as _i3.SendAsset);
  @override
  String get receivingAddress =>
      (super.noSuchMethod(Invocation.getter(#receivingAddress), returnValue: '')
          as String);
  @override
  String get requiredString =>
      (super.noSuchMethod(Invocation.getter(#requiredString), returnValue: '')
          as String);
  @override
  String get insufficientString => (super
          .noSuchMethod(Invocation.getter(#insufficientString), returnValue: '')
      as String);
  @override
  String get tooManyDecimalPlacesString =>
      (super.noSuchMethod(Invocation.getter(#tooManyDecimalPlacesString),
          returnValue: '') as String);
  @override
  String get gasEstimateNotReadyString =>
      (super.noSuchMethod(Invocation.getter(#gasEstimateNotReadyString),
          returnValue: '') as String);
  @override
  _i5.Stream<_i4.SendAmountBlocState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: _i5.Stream<_i4.SendAmountBlocState>.empty())
          as _i5.Stream<_i4.SendAmountBlocState>);
  @override
  _i5.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> showNext(String? note, String? amount) =>
      (super.noSuchMethod(Invocation.method(#showNext, [note, amount]),
              returnValue: _i5.Future<void>.value(),
              returnValueForMissingStub: _i5.Future<void>.value())
          as _i5.Future<void>);
}
